import { Pet, ShelterProfile } from './types';

export const INITIAL_SHELTER: ShelterProfile = {
  id: 1,
  shelter_name: 'Haven Paws Animal Adoption Center',
  tagline: 'Connecting Loving Families with Pets in Need',
  bio: 'Founded in 2018, Haven Paws is a non-profit, cage-free rescue sanctuary committed to giving every companion animal a second chance at life. We provide comprehensive veterinary care, behavioral rehabilitation, and gentle socialization before connecting our rescues with loving forever homes.',
  phone: '(555) 234-5678',
  email: 'adoptions@havenpaws.org',
  address: '742 Evergreen Terrace, Springfield, OR 97477',
  opening_hours: 'Tuesday – Sunday: 10:00 AM – 5:30 PM (Closed Mondays for sanitization)',
  banner_image_path: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80',
  updated_at: new Date().toISOString(),
};

export const INITIAL_PETS: Pet[] = [
  {
    id: 1,
    name: 'Milo',
    type: 'Dog',
    breed: 'Golden Retriever Mix',
    age: '2 years',
    gender: 'Male',
    description: 'Milo is an affectionate, energetic young pup who loves morning fetch, belly rubs, and learning new agility tricks. Great with children and fellow dogs. House-trained and crate-trained.',
    status: 'Available',
    image_path: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: 2,
    name: 'Luna',
    type: 'Cat',
    breed: 'Domestic Short Hair',
    age: '1 year',
    gender: 'Female',
    description: 'Luna is a quiet, purring cuddle enthusiast. She adores sunny windowsills, laser pointers, and curling up beside you while you read. Very gentle temperament and litter-box pro.',
    status: 'Available',
    image_path: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-02T11:30:00Z',
    updated_at: '2024-03-02T11:30:00Z',
  },
  {
    id: 3,
    name: 'Barnaby',
    type: 'Rabbit',
    breed: 'Holland Lop',
    age: '8 months',
    gender: 'Male',
    description: 'Barnaby is a gentle, velvet-soft bunny who does cute binkies when excited. He is litter-box trained, loves fresh parsley and crisp timothy hay, and enjoys quiet head strokes.',
    status: 'Pending',
    image_path: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-03T14:15:00Z',
    updated_at: '2024-03-03T14:15:00Z',
  },
  {
    id: 4,
    name: 'Pip & Squeak',
    type: 'Bird',
    breed: 'Cockatiel Pair',
    age: '3 years',
    gender: 'Unknown',
    description: 'A bonded pair of cheerful whistling cockatiels that must be adopted together. They love head scratches, fresh apple slices, and whistle sweet morning melodies.',
    status: 'Available',
    image_path: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-04T09:00:00Z',
    updated_at: '2024-03-04T09:00:00Z',
  },
  {
    id: 5,
    name: 'Copper',
    type: 'Dog',
    breed: 'Beagle Hound',
    age: '4 years',
    gender: 'Male',
    description: 'Copper has big soulful hazel eyes and an inquisitive tracking nose. He enjoys leisurely nature walks, chew toys, and sleeping near warm blankets after an outdoor adventure.',
    status: 'Available',
    image_path: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-05T13:45:00Z',
    updated_at: '2024-03-05T13:45:00Z',
  },
  {
    id: 6,
    name: 'Willow',
    type: 'Cat',
    breed: 'Calico Longhair',
    age: '3 years',
    gender: 'Female',
    description: 'Willow is majestic, calm, and regal. She was recently adopted by a wonderful family and is now thriving in her forever home with two kids and a spacious sunroom!',
    status: 'Adopted',
    image_path: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-06T15:20:00Z',
    updated_at: '2024-03-06T15:20:00Z',
  },
  {
    id: 7,
    name: 'Rocky',
    type: 'Dog',
    breed: 'Australian Shepherd',
    age: '1.5 years',
    gender: 'Male',
    description: 'High-spirited working dog looking for an active hiking or running companion. Extremely smart, attentive, and loyal. Working with a foster family on trail manners.',
    status: 'Pending',
    image_path: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-07T16:00:00Z',
    updated_at: '2024-03-07T16:00:00Z',
  },
  {
    id: 8,
    name: 'Ziggy',
    type: 'Other',
    breed: 'Guinea Pig Duo',
    age: '1 year',
    gender: 'Male',
    description: 'Ziggy and his brother make joyful chirping sounds when the vegetable drawer opens! Very friendly, gentle with children, and easy to care for with clean daily hay.',
    status: 'Available',
    image_path: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80',
    created_at: '2024-03-08T12:10:00Z',
    updated_at: '2024-03-08T12:10:00Z',
  },
];
